# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'to-do-list-app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 480)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #E8F4FD;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.task_list = QtWidgets.QListWidget(self.centralwidget)
        self.task_list.setGeometry(QtCore.QRect(20, 70, 191, 281))
        self.task_list.setStyleSheet("QListWidget {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #E8F4FD;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #89CFF0;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #D6EEFB;\n"
"}")
        self.task_list.setObjectName("task_list")
        self.priority_combo = QtWidgets.QComboBox(self.centralwidget)
        self.priority_combo.setGeometry(QtCore.QRect(220, 260, 101, 31))
        self.priority_combo.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #89CFF0;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #89CFF0;\n"
"    margin-right: 10px;\n"
"}")
        self.priority_combo.setEditable(False)
        self.priority_combo.setObjectName("priority_combo")
        self.priority_combo.addItem("")
        self.priority_combo.addItem("")
        self.priority_combo.addItem("")
        self.due_date = QtWidgets.QDateEdit(self.centralwidget)
        self.due_date.setGeometry(QtCore.QRect(330, 260, 111, 31))
        self.due_date.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #89CFF0;\n"
"}")
        self.due_date.setCalendarPopup(True)
        self.due_date.setObjectName("due_date")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(220, 300, 71, 41))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.add_btn.setStyleSheet("QPushButton {\n"
"    background-color: #89CFF0;\n"
"    color: #000000;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A8DAF5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6BB5E0;\n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(300, 300, 71, 41))
        self.delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFB6C1;\n"
"    color: #000000;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFC0CB;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF9EAF;\n"
"}")
        self.delete_btn.setObjectName("delete_btn")
        self.stats_label = QtWidgets.QLabel(self.centralwidget)
        self.stats_label.setGeometry(QtCore.QRect(20, 370, 421, 41))
        self.stats_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stats_label.setStyleSheet("QLabel {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"}")
        self.stats_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stats_label.setObjectName("stats_label")
        self.title_input = QtWidgets.QLineEdit(self.centralwidget)
        self.title_input.setGeometry(QtCore.QRect(220, 70, 221, 41))
        self.title_input.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #89CFF0;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.title_input.setObjectName("title_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 181, 41))
        self.label.setStyleSheet("QLabel {\n"
"    color: #4A90E2;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 30, 221, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #4A90E2;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.desc_input = QtWidgets.QTextEdit(self.centralwidget)
        self.desc_input.setGeometry(QtCore.QRect(220, 120, 221, 111))
        self.desc_input.setStyleSheet("QTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #000000;\n"
"    border: 2px solid #B0D4F1;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #89CFF0;\n"
"}")
        self.desc_input.setObjectName("desc_input")
        self.priority_label = QtWidgets.QLabel(self.centralwidget)
        self.priority_label.setGeometry(QtCore.QRect(230, 240, 91, 20))
        self.priority_label.setStyleSheet("color: #000000; font-size: 13px;")
        self.priority_label.setObjectName("priority_label")
        self.duedate_label = QtWidgets.QLabel(self.centralwidget)
        self.duedate_label.setGeometry(QtCore.QRect(340, 240, 91, 20))
        self.duedate_label.setStyleSheet(" color: #000000; font-size: 13px; ")
        self.duedate_label.setObjectName("duedate_label")
        self.delete_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn_2.setGeometry(QtCore.QRect(380, 300, 71, 41))
        self.delete_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: #C1FFC1;\n"
"    color: #000000;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D4FFD4;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A8E6A8;\n"
"}")
        self.delete_btn_2.setObjectName("delete_btn_2")
        self.priority_combo.raise_()
        self.due_date.raise_()
        self.add_btn.raise_()
        self.delete_btn.raise_()
        self.stats_label.raise_()
        self.task_list.raise_()
        self.title_input.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.desc_input.raise_()
        self.priority_label.raise_()
        self.duedate_label.raise_()
        self.delete_btn_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 463, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.priority_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To-do-List-App"))
        self.priority_combo.setCurrentText(_translate("MainWindow", "low"))
        self.priority_combo.setProperty("items", _translate("MainWindow", "\n"
"      "))
        self.priority_combo.setProperty("item", _translate("MainWindow", "low"))
        self.priority_combo.setItemText(0, _translate("MainWindow", "low"))
        self.priority_combo.setItemText(1, _translate("MainWindow", "medium"))
        self.priority_combo.setItemText(2, _translate("MainWindow", "high"))
        self.due_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.add_btn.setText(_translate("MainWindow", "+ADD"))
        self.delete_btn.setText(_translate("MainWindow", "DELETE"))
        self.stats_label.setText(_translate("MainWindow", "📊 Statistics | Total: 0 | Completed: 0"))
        self.title_input.setPlaceholderText(_translate("MainWindow", "Enter task title"))
        self.label.setText(_translate("MainWindow", "MY TASKS"))
        self.label_2.setText(_translate("MainWindow", "TASK DETAILS"))
        self.desc_input.setPlaceholderText(_translate("MainWindow", "Enter description"))
        self.priority_label.setText(_translate("MainWindow", "Priority"))
        self.duedate_label.setText(_translate("MainWindow", "Due Date"))
        self.delete_btn_2.setText(_translate("MainWindow", "DONE"))
